version: '3.6'
services:
    hello:
        build:
            context: .
            dockerfile: Dockerfile.service
        image: hello:v1
        container_name: hello
    envoy:
        build:
            context: .
            dockerfile: Dockerfile.envoy
        image: hello-envoy:v1
        container_name: hello_envoy
        ports:
            - 9901:9901
            - 8080:8080            
        depends_on: 
            - hello