version: '3.6'
services:
  books:
    build:
      context: .
      dockerfile: Dockerfile.service
    image: books:v1
    container_name: books
  envoy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    image: books-envoy:v1
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    container_name: books_envoy
    ports:
        - 9901:9901
        - 8080:8080            
    depends_on: 
        - books